### ISSUE TITLE
convert pfm to png

### ISSUE THREAD

**Issue by TrackingBird** [roboception/cvkit#3]
Thanks for your works. Sorry for bothering you. I am wondering can CVKIT convert pfm image into png?

**Comment by heikohimu** [comment]
Yes, with the command line tool:
`imgcmd input_image.pfm -out output_image.png`
There are also command line parameters to scale the values or add an offset if necessary.

**Comment by TrackingBird** [comment]
@heikohimu sorry to bother you. I did the command as yours, but exception shows:
````
 $imgcmd 20.pfm -out output_image.png
IO exception: Saving this image type is not implemented! (output_image.png)
````
Can you give me some suggestion? Thanks.

**Comment by heikohimu** [comment]
Sorry, my answer was incomplete. Since PNG does not support floating point values, you need to cast the values either to 8 bits with the parameter -u8 or to 16 bits with the parameter -u16 before storing. Additionally, the parameters -mul and -add might be useful for scaling and adding an offset to the values, i.e.:

`imgcmd input_image.pfm -mul 4 -u16 -out output_image.png`

This will multiply all floating point values with 4 and cast them to 16 bit, before storing them as PNG. All operations are executed in the order of the parameters. Have a look at the help page by executing the binary without any parameters.
